name: palm_challenge
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  shared_preferences: ^2.5.3
  get_it: ^8.0.3
  flutter_bloc: ^9.1.0
  equatable: ^2.0.7
  freezed: ^3.0.6
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  cached_network_image: ^3.4.1
  intl: ^0.20.2
  sqflite: ^2.4.2
  connectivity_plus: ^6.1.4
  path: ^1.9.1
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.5.4
  json_serializable: ^6.9.5

flutter:
  uses-material-design: true
